public class AP39_BackResults {
    
    @AuraEnabled
    public Boolean success {get;set;}
    @AuraEnabled
    public String message {get;set;}
    @AuraEnabled
    public String str1 {get;set;}
    @AuraEnabled
    public Decimal cur1 {get;set;}
    @AuraEnabled
    public Decimal cur2 {get;set;}
    @AuraEnabled
    public Decimal dec1 {get;set;}
    //@AuraEnabled
    //public Order ord1 {get;set;}
    
}